version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sellia_chat
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - app-network
      
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/sellia_chat
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      
volumes:
  mongodb:
